### ISSUE TITLE
Initial product backlog

### ISSUE THREAD

**Issue by 0Micah** [AshleyConnearney13/CubesatCapstone#2]
### Sprint 1:

**TODO:**

- [x] Review GNURadio Documentation (_Casey, Micah, and Ashley_)
- [x] Identify Software requirements (_Casey, Micah, and Ashley_)
- [x] Research FCC ( All )
- [x] Choose a coding language  (_Casey, Micah, and Ashley_)
- [x] Find software to interface with (_Casey, Micah, and Ashley_)

**IN PROGRESS:**
- [x] Create Jira backlog 
- [x] Determine UI Requirements (_Casey, Micah, and Ashley_)
- [x] Create GitHub repository (_Ashley_)
- [x] Create Jira Backlog (_Peyton_, _Andres_) 
- [x] Create Github repository(Ashley, Micah, Casey)
- [x] Create Product Vision Statement (_Ashley_, _Lucien_)

Once an item is complete, it shall have a check in its respective box.

**Comment by AshleyConnearney13** [comment]
![JiraSprintOneBacklog](https://github.com/user-attachments/assets/ec0c89cd-999e-428f-a2dd-f20a39b594b1)
